codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "60...90"

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

ignore:
  - "scripts/**/*"

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: no