version: 2
jobs:
  build:
    working_directory: /go/src/github.com/gojek/kat
    docker:
    - image: circleci/golang:1.11
    steps:
    - checkout
    - setup_remote_docker:
        docker_layer_caching: false
    - restore_cache:
        keys:
        - vendor-pkg-{{ checksum "go.sum" }}
        - vendor-pkg-
    - run:
        name: Install Dependencies
        command: |
          make setup
    - save_cache:
        paths:
        - ./vendor
        - "/go/pkg"
        key: vendor-pkg-{{ checksum "go.sum" }}
    - run:
        name: Check Quality
        command: |
          env GO111MODULE=on go mod verify
          env GO111MODULE=on make clean check-quality golangci
    - run:
        name: Build
        command: |
          env GO111MODULE=on go mod verify
          env GO111MODULE=on make clean build


  test:
    working_directory: /go/src/github.com/gojek/kat
    docker:
    - image: circleci/golang:1.11
    steps:
    - checkout
    - setup_remote_docker:
        docker_layer_caching: false
    - restore_cache:
        keys:
        - vendor-pkg-{{ checksum "go.sum" }}
        - vendor-pkg-
    - run:
        name: Install Dependencies
        command: |
          make setup
    - save_cache:
        paths:
        - ./vendor
        - "/go/pkg"
        key: vendor-pkg-{{ checksum "go.sum" }}
    - run:
        name: Run tests
        command: |
          env GO111MODULE=on go mod verify
          env GO111MODULE=on make test


  release:
    working_directory: /go/src/github.com/gojek/kat
    docker:
      - image: circleci/golang:1.11
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - restore_cache:
          keys:
            - vendor-pkg-{{ checksum "go.sum" }}
            - vendor-pkg-
      - run:
          name: Install Dependencies
          command: |
            env GO111MODULE=on go mod vendor
      - save_cache:
          paths:
            - ./vendor
            - "/go/pkg"
          key: vendor-pkg-{{ checksum "go.sum" }}
      - run:
          name: Release go binary
          command: |
            env GO111MODULE=on make
            curl -sL https://git.io/goreleaser | bash

workflows:
  version: 2
  build-test-release:
    jobs:
    - build
    - test:
        requires:
          - build
    - release:
        requires:
          - test
