version: 2
jobs:
  test:
    working_directory: /go/src/github.com/gojekfarm/kat
    docker:
    - image: circleci/golang:1.11
    steps:
    - checkout
    - setup_remote_docker:
        docker_layer_caching: true
    - restore_cache:
        keys:
        - vendor-pkg-{{ checksum "go.sum" }}
        - vendor-pkg-
    - run:
        name: Install Dependencies
        command: |
          make setup
    - save_cache:
        paths:
        - ./vendor
        - "/go/pkg"
        key: vendor-pkg-{{ checksum "go.sum" }}
    - run:
        name: Run tests
        command: |
          env GO111MODULE=on go mod verify
          env GO111MODULE=on CGO_ENABLED=0 make

workflows:
  version: 2
  build_and_test:
    jobs:
    - test
